services:
  api:
    build:
      context: ./DJJM.API
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Updated to match the ASPNETCORE_URLS in the Dockerfile
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - djjm-network

  finance:
    build:
      context: ./DJJM.Finance
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Exposing the WASM project on port 5000
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_BASE_URL=http://api:5220 # Updated API service URL to match the API's port
    networks:
      - djjm-network

networks:
  djjm-network:
    driver: bridge
